apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
    template:
      metadata:
        labels:
          component: server
      spec:
        containers:
          - name: server
            image: atelierkarin/test-server
            ports:
              - containerPort: 80